//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basta.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Basta.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a to English.
        /// </summary>
        public static string changeLanguageButton {
            get {
                return ResourceManager.GetString("changeLanguageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string ChangePassword_Button_Change {
            get {
                return ResourceManager.GetString("ChangePassword_Button_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes ingresar en lo campos de texto la contraseña por la cual deseas cambiar. Ambas contraseñas deben ser iguales..
        /// </summary>
        public static string ChangePassword_Label_Description {
            get {
                return ResourceManager.GetString("ChangePassword_Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string ChangePassword_Label_Password {
            get {
                return ResourceManager.GetString("ChangePassword_Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repetir contraseña.
        /// </summary>
        public static string ChangePassword_Label_RepeatPassword {
            get {
                return ResourceManager.GetString("ChangePassword_Label_RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string ChangePassword_Label_Toptitle {
            get {
                return ResourceManager.GetString("ChangePassword_Label_Toptitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat de la sala actual.
        /// </summary>
        public static string Chat_GlobalChat {
            get {
                return ResourceManager.GetString("Chat_GlobalChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios conectados.
        /// </summary>
        public static string Chat_UsersConnected {
            get {
                return ResourceManager.GetString("Chat_UsersConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador.
        /// </summary>
        public static string ChatTypePlayer {
            get {
                return ResourceManager.GetString("ChatTypePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string Game_Button_Next {
            get {
                return ResourceManager.GetString("Game_Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Basta!.
        /// </summary>
        public static string Game_Button_Stop {
            get {
                return ResourceManager.GetString("Game_Button_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Haz presiona el botón ¡Basta!, se avisará a todos los jugadores que has terminado y su tiempo se disminuirá a 15 segundos..
        /// </summary>
        public static string Game_Button_Stoppressed {
            get {
                return ResourceManager.GetString("Game_Button_Stoppressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Animal.
        /// </summary>
        public static string Game_Category_Animal {
            get {
                return ResourceManager.GetString("Game_Category_Animal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        public static string Game_Category_City {
            get {
                return ResourceManager.GetString("Game_Category_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color.
        /// </summary>
        public static string Game_Category_Color {
            get {
                return ResourceManager.GetString("Game_Category_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        public static string Game_Category_Country {
            get {
                return ResourceManager.GetString("Game_Category_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fruta o verdura.
        /// </summary>
        public static string Game_Category_Fruitvegetable {
            get {
                return ResourceManager.GetString("Game_Category_Fruitvegetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        public static string Game_Category_Lastname {
            get {
                return ResourceManager.GetString("Game_Category_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Game_Category_Name {
            get {
                return ResourceManager.GetString("Game_Category_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cosa.
        /// </summary>
        public static string Game_Category_Object {
            get {
                return ResourceManager.GetString("Game_Category_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (ganador absoluto).
        /// </summary>
        public static string Game_Label_Absolutwinner {
            get {
                return ResourceManager.GetString("Game_Label_Absolutwinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo restante:.
        /// </summary>
        public static string Game_Label_Counter {
            get {
                return ResourceManager.GetString("Game_Label_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa una palabra que esté en el ámbito de: .
        /// </summary>
        public static string Game_Label_Enterword {
            get {
                return ResourceManager.GetString("Game_Label_Enterword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si ingresas una palabra que no haya sido ingresada por otro jugador entonces recibirás 150 puntos. Si ingresas una palabra que haya sido ingresada por otro jugador entonecs recibirás 100 puntos. Y por último, si ingresas una palabra que no sea válida entonces recibirás 0 puntos. Evita ingresar insultos porque puedes recibir sanciones..
        /// </summary>
        public static string Game_Label_Info {
            get {
                return ResourceManager.GetString("Game_Label_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Recuerda que al dar clic en &quot;Siguiente&quot; no puedes retroceder!.
        /// </summary>
        public static string Game_Label_Infotool {
            get {
                return ResourceManager.GetString("Game_Label_Infotool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La letra inicial de las palabras:.
        /// </summary>
        public static string Game_Label_LetterAssigned {
            get {
                return ResourceManager.GetString("Game_Label_LetterAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Letra seleccionada:.
        /// </summary>
        public static string Game_Label_Lettertoplabel {
            get {
                return ResourceManager.GetString("Game_Label_Lettertoplabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empate..
        /// </summary>
        public static string Game_Label_Nowinner {
            get {
                return ResourceManager.GetString("Game_Label_Nowinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ronda.
        /// </summary>
        public static string Game_Label_Roundinitialize {
            get {
                return ResourceManager.GetString("Game_Label_Roundinitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rondas:.
        /// </summary>
        public static string Game_Label_Rounds {
            get {
                return ResourceManager.GetString("Game_Label_Rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Las respuestas se han guardado!.
        /// </summary>
        public static string Game_Label_Saveanswers {
            get {
                return ResourceManager.GetString("Game_Label_Saveanswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntuación obtenida:.
        /// </summary>
        public static string Game_Label_ScoreWon {
            get {
                return ResourceManager.GetString("Game_Label_ScoreWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  segundos.
        /// </summary>
        public static string Game_Label_Seconds {
            get {
                return ResourceManager.GetString("Game_Label_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comenzando....
        /// </summary>
        public static string Game_Label_Starting {
            get {
                return ResourceManager.GetString("Game_Label_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (ganador de la ronda).
        /// </summary>
        public static string Game_Label_Winnerroundtext {
            get {
                return ResourceManager.GetString("Game_Label_Winnerroundtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa una palabra que coincida con el ámbito.
        /// </summary>
        public static string Game_TextInput_Insert {
            get {
                return ResourceManager.GetString("Game_TextInput_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar.
        /// </summary>
        public static string Lobby_Button_Configuregame {
            get {
                return ResourceManager.GetString("Lobby_Button_Configuregame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar sala.
        /// </summary>
        public static string Lobby_Button_Configureroom {
            get {
                return ResourceManager.GetString("Lobby_Button_Configureroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar sala.
        /// </summary>
        public static string Lobby_Button_Destroyroom {
            get {
                return ResourceManager.GetString("Lobby_Button_Destroyroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string Lobby_Button_Exit {
            get {
                return ResourceManager.GetString("Lobby_Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Comenzar!.
        /// </summary>
        public static string Lobby_Button_Play {
            get {
                return ResourceManager.GetString("Lobby_Button_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tú.
        /// </summary>
        public static string Lobby_Chat_You {
            get {
                return ResourceManager.GetString("Lobby_Chat_You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar juego.
        /// </summary>
        public static string Lobby_Label_Configuregame {
            get {
                return ResourceManager.GetString("Lobby_Label_Configuregame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorias de palabras.
        /// </summary>
        public static string Lobby_Label_Gamecategory {
            get {
                return ResourceManager.GetString("Lobby_Label_Gamecategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Límite de jugadores: .
        /// </summary>
        public static string Lobby_Label_Playerslimit {
            get {
                return ResourceManager.GetString("Lobby_Label_Playerslimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de sala: .
        /// </summary>
        public static string Lobby_Label_Roomcode {
            get {
                return ResourceManager.GetString("Lobby_Label_Roomcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración de sala.
        /// </summary>
        public static string Lobby_Label_Roomsettings {
            get {
                return ResourceManager.GetString("Lobby_Label_Roomsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privacidad de la sala: .
        /// </summary>
        public static string Lobby_Label_Roomstate {
            get {
                return ResourceManager.GetString("Lobby_Label_Roomstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Límite de rondas: .
        /// </summary>
        public static string Lobby_Label_Roundslimit {
            get {
                return ResourceManager.GetString("Lobby_Label_Roundslimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo de ronda: .
        /// </summary>
        public static string Lobby_Label_Roundstempo {
            get {
                return ResourceManager.GetString("Lobby_Label_Roundstempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo de terminar ronda.
        /// </summary>
        public static string Lobby_Label_Timetoendround {
            get {
                return ResourceManager.GetString("Lobby_Label_Timetoendround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando jugadores....
        /// </summary>
        public static string Lobby_Label_Waitingfor {
            get {
                return ResourceManager.GetString("Lobby_Label_Waitingfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una sala para ingresar.
        /// </summary>
        public static string Lobby_ListView_Select {
            get {
                return ResourceManager.GetString("Lobby_ListView_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡No hay la suficiente cantidad de jugadores!.
        /// </summary>
        public static string Lobby_Message_Playersnotenought {
            get {
                return ResourceManager.GetString("Lobby_Message_Playersnotenought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla de clasificaciones.
        /// </summary>
        public static string Lobby_TextBlock_Clasification {
            get {
                return ResourceManager.GetString("Lobby_TextBlock_Clasification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  puntos ganados.
        /// </summary>
        public static string Lobby_TextBlock_PointsWon {
            get {
                return ResourceManager.GetString("Lobby_TextBlock_PointsWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Comienza a jugar ahora!.
        /// </summary>
        public static string LobbyWindow_TextBox_StartGame {
            get {
                return ResourceManager.GetString("LobbyWindow_TextBox_StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string login_Button_signUp {
            get {
                return ResourceManager.GetString("login_Button_signUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Haz olvidado tu contraseña?.
        /// </summary>
        public static string login_Label_forgottenPassword {
            get {
                return ResourceManager.GetString("login_Label_forgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Haz clic aquí.
        /// </summary>
        public static string login_Label_forgottenPassword2 {
            get {
                return ResourceManager.GetString("login_Label_forgottenPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string login_Label_login {
            get {
                return ResourceManager.GetString("login_Label_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el usuario o correo.
        /// </summary>
        public static string login_TextField_userOrEmail {
            get {
                return ResourceManager.GetString("login_TextField_userOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Main_Button_Cancel {
            get {
                return ResourceManager.GetString("Main_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string Main_Button_Configuration {
            get {
                return ResourceManager.GetString("Main_Button_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear sala.
        /// </summary>
        public static string Main_Button_Createroom {
            get {
                return ResourceManager.GetString("Main_Button_Createroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string Main_Button_Exit {
            get {
                return ResourceManager.GetString("Main_Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        public static string Main_Button_Joinroom {
            get {
                return ResourceManager.GetString("Main_Button_Joinroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar.
        /// </summary>
        public static string Main_Button_Play {
            get {
                return ResourceManager.GetString("Main_Button_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Main_Button_Saveconfiguration {
            get {
                return ResourceManager.GetString("Main_Button_Saveconfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una sala para unirte..
        /// </summary>
        public static string Main_Button_Selectroom {
            get {
                return ResourceManager.GetString("Main_Button_Selectroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string Main_ChoiceBox_English {
            get {
                return ResourceManager.GetString("Main_ChoiceBox_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string Main_ChoiceBox_Spanish {
            get {
                return ResourceManager.GetString("Main_ChoiceBox_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string Main_Label_Language {
            get {
                return ResourceManager.GetString("Main_Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privada.
        /// </summary>
        public static string Main_Label_Private {
            get {
                return ResourceManager.GetString("Main_Label_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pública.
        /// </summary>
        public static string Main_Label_Public {
            get {
                return ResourceManager.GetString("Main_Label_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limite de personas.
        /// </summary>
        public static string Main_Label_Roommemberlimit {
            get {
                return ResourceManager.GetString("Main_Label_Roommemberlimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limite de rondas.
        /// </summary>
        public static string Main_Label_Roomroundlimit {
            get {
                return ResourceManager.GetString("Main_Label_Roomroundlimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar sala.
        /// </summary>
        public static string Main_Label_Roomsettings {
            get {
                return ResourceManager.GetString("Main_Label_Roomsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privacidad de sala.
        /// </summary>
        public static string Main_Label_Roomstate {
            get {
                return ResourceManager.GetString("Main_Label_Roomstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo de ronda.
        /// </summary>
        public static string Main_Label_Roomtime {
            get {
                return ResourceManager.GetString("Main_Label_Roomtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string Main_Label_Settings {
            get {
                return ResourceManager.GetString("Main_Label_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volumen de música.
        /// </summary>
        public static string Main_Label_Volume {
            get {
                return ResourceManager.GetString("Main_Label_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Main_TextField_Cancel {
            get {
                return ResourceManager.GetString("Main_TextField_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código de sala.
        /// </summary>
        public static string Main_TextField_Code {
            get {
                return ResourceManager.GetString("Main_TextField_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe algo para enviar....
        /// </summary>
        public static string MainLobby_TextField_Chat {
            get {
                return ResourceManager.GetString("MainLobby_TextField_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar código a correo.
        /// </summary>
        public static string recoveryPassword_Button_Send {
            get {
                return ResourceManager.GetString("recoveryPassword_Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar código.
        /// </summary>
        public static string recoveryPassword_Button_Verify {
            get {
                return ResourceManager.GetString("recoveryPassword_Button_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes ingresar tu correo electrónico para que Basta te envie un código de recuperación a tu correo. El código que recibirás debes ingresarlo en uno de los campos de texto.
        /// </summary>
        public static string recoveryPassword_Label_Description {
            get {
                return ResourceManager.GetString("recoveryPassword_Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string recoveryPassword_Label_Email {
            get {
                return ResourceManager.GetString("recoveryPassword_Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de recuperación.
        /// </summary>
        public static string recoveryPassword_Label_Recovery {
            get {
                return ResourceManager.GetString("recoveryPassword_Label_Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar contraseña.
        /// </summary>
        public static string recoveryPassword_Label_RecoveryPassword {
            get {
                return ResourceManager.GetString("recoveryPassword_Label_RecoveryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;html&gt;
        ///&lt;body&gt;
        ///&lt;div style=\border-style:solid;border-color:#323232;border-width:1px 1px 1px 1px;text-align:justify;background-color:#f8f8f8;width:80% !important;height:80% !important;padding:3% 3% 3% 3%;\&gt;
        ///      &lt;h1 style=\color:#8a8a8a;font-family:sans-serif;text-align:left;\&gt; Recuperación de contraseña &lt;/h1&gt;
        ///      &lt;p style=\font-family:sans-serif;\&gt; Recibimos una solicitud para restablecer tu contraseña del &lt;b&gt;Sistema Basta&lt;/b&gt;&lt;/p&gt;
        ///      &lt;p style=\font-family:sans-serif;\&gt; Ingresa el siguiente código en el [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string recoveryPassword_Message_Contenthtml {
            get {
                return ResourceManager.GetString("recoveryPassword_Message_Contenthtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código de recuperación.
        /// </summary>
        public static string recoveryPassword_TextFiel_Recovery {
            get {
                return ResourceManager.GetString("recoveryPassword_TextFiel_Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu correo electrónico.
        /// </summary>
        public static string recoveryPassword_TextField_Email {
            get {
                return ResourceManager.GetString("recoveryPassword_TextField_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de cuenta.
        /// </summary>
        public static string signUp_Label_AccountInformation {
            get {
                return ResourceManager.GetString("signUp_Label_AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edad.
        /// </summary>
        public static string signUp_Label_Age {
            get {
                return ResourceManager.GetString("signUp_Label_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        public static string signUp_Label_Country {
            get {
                return ResourceManager.GetString("signUp_Label_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string signUp_Label_Email {
            get {
                return ResourceManager.GetString("signUp_Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string signUp_Label_LastName {
            get {
                return ResourceManager.GetString("signUp_Label_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string signUp_Label_Name {
            get {
                return ResourceManager.GetString("signUp_Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string signUp_Label_Password {
            get {
                return ResourceManager.GetString("signUp_Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información personal.
        /// </summary>
        public static string signUp_Label_PersonalInformation {
            get {
                return ResourceManager.GetString("signUp_Label_PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string signUp_Label_signUp {
            get {
                return ResourceManager.GetString("signUp_Label_signUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar cuenta.
        /// </summary>
        public static string signUp_Label_SignUpAccount {
            get {
                return ResourceManager.GetString("signUp_Label_SignUpAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string signUp_Label_Username {
            get {
                return ResourceManager.GetString("signUp_Label_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu edad.
        /// </summary>
        public static string signUp_TextField_AgeText {
            get {
                return ResourceManager.GetString("signUp_TextField_AgeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu país.
        /// </summary>
        public static string signUp_TextField_Country {
            get {
                return ResourceManager.GetString("signUp_TextField_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu correo electrónico.
        /// </summary>
        public static string signUp_TextField_Email {
            get {
                return ResourceManager.GetString("signUp_TextField_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tus apellidos.
        /// </summary>
        public static string signUp_TextField_LastName {
            get {
                return ResourceManager.GetString("signUp_TextField_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu nombre.
        /// </summary>
        public static string signUp_TextField_Name {
            get {
                return ResourceManager.GetString("signUp_TextField_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu nombre de usuario.
        /// </summary>
        public static string signUp_TextField_Username {
            get {
                return ResourceManager.GetString("signUp_TextField_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Límite de intentos alcanzado! ¡Espera 10 minutos!.
        /// </summary>
        public static string SystemAttemptsLimitReached {
            get {
                return ResourceManager.GetString("SystemAttemptsLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡No se completo el proceso de recuperación de código!.
        /// </summary>
        public static string SystemErrorSendMessage {
            get {
                return ResourceManager.GetString("SystemErrorSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡El correo electrónico ya está registrado!.
        /// </summary>
        public static string SystemExistingEmail {
            get {
                return ResourceManager.GetString("SystemExistingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Tu nombre de usuario ya está siendo usado!.
        /// </summary>
        public static string SystemExistingUsername {
            get {
                return ResourceManager.GetString("SystemExistingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Ha ocurrido un error y se ha registrado en un archivo!.
        /// </summary>
        public static string SystemFatalError {
            get {
                return ResourceManager.GetString("SystemFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡La sala está llena!.
        /// </summary>
        public static string SystemGameFull {
            get {
                return ResourceManager.GetString("SystemGameFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡El código no coincide, revisalo!.
        /// </summary>
        public static string SystemInvalidCode {
            get {
                return ResourceManager.GetString("SystemInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Los datos son erroneos!.
        /// </summary>
        public static string SystemInvalidData {
            get {
                return ResourceManager.GetString("SystemInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cuenta ya ha iniciado sesión.
        /// </summary>
        public static string SystemLoginAccountAlreadyLogged {
            get {
                return ResourceManager.GetString("SystemLoginAccountAlreadyLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Tu cuenta ha sido baneada!.
        /// </summary>
        public static string SystemLoginAccountBanned {
            get {
                return ResourceManager.GetString("SystemLoginAccountBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Te has equivocado! Verifica tus datos.
        /// </summary>
        public static string SystemLoginError {
            get {
                return ResourceManager.GetString("SystemLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Debes esperar 10 minutos!.
        /// </summary>
        public static string SystemLoginWaitMinutes {
            get {
                return ResourceManager.GetString("SystemLoginWaitMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Se registró un problema con la base de datos!.
        /// </summary>
        public static string SystemLostConnection {
            get {
                return ResourceManager.GetString("SystemLostConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Alerta!.
        /// </summary>
        public static string SystemMessageTitle {
            get {
                return ResourceManager.GetString("SystemMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡El correo electrónico no está registrado!.
        /// </summary>
        public static string SystemNoExistingEmail {
            get {
                return ResourceManager.GetString("SystemNoExistingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo cambiar la contraseña ¡Intenta más tarde!.
        /// </summary>
        public static string SystemPasswordChangingError {
            get {
                return ResourceManager.GetString("SystemPasswordChangingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Las contraseñas no coinciden!.
        /// </summary>
        public static string SystemPasswordNoMatch {
            get {
                return ResourceManager.GetString("SystemPasswordNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Has sido expulsado de la sala!.
        /// </summary>
        public static string SystemPlayerKicked {
            get {
                return ResourceManager.GetString("SystemPlayerKicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡No se encontró la sala!.
        /// </summary>
        public static string SystemRoomNotFound {
            get {
                return ResourceManager.GetString("SystemRoomNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor está presentando problemas..
        /// </summary>
        public static string SystemServerNotFound {
            get {
                return ResourceManager.GetString("SystemServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No debe contener carácteres extraños como ¡?=)(/&amp;%$#&quot;!!¨*¨[] ni números.
        /// </summary>
        public static string Tooltip_SignUp_Country {
            get {
                return ResourceManager.GetString("Tooltip_SignUp_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe tener el formato xxxxx@xxxxx.xxx.
        /// </summary>
        public static string Tooltip_SignUp_Email {
            get {
                return ResourceManager.GetString("Tooltip_SignUp_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No debe contener carácteres extraños como ¡?=)(/&amp;%$#&quot;!!¨*¨[] ni números.
        /// </summary>
        public static string Tooltip_SignUp_LastName {
            get {
                return ResourceManager.GetString("Tooltip_SignUp_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No debe contener carácteres extraños como ¡?=)(/&amp;%$#&quot;!!¨*¨[] ni números.
        /// </summary>
        public static string Tooltip_SignUp_Name {
            get {
                return ResourceManager.GetString("Tooltip_SignUp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe contener por lo menos 8 carácteres..
        /// </summary>
        public static string Tooltip_SignUp_Password {
            get {
                return ResourceManager.GetString("Tooltip_SignUp_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No debe contener carácteres extraños como ¡?=)(/&amp;%$#&quot;!!¨*¨[].
        /// </summary>
        public static string Tooltip_SignUp_Username {
            get {
                return ResourceManager.GetString("Tooltip_SignUp_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsar.
        /// </summary>
        public static string UserConnectedLobby_Button_KickPlayer {
            get {
                return ResourceManager.GetString("UserConnectedLobby_Button_KickPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportar.
        /// </summary>
        public static string UserConnectedLobby_Button_ReportPlayer {
            get {
                return ResourceManager.GetString("UserConnectedLobby_Button_ReportPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar mensaje.
        /// </summary>
        public static string UserConnectedLobby_Button_SendMessage {
            get {
                return ResourceManager.GetString("UserConnectedLobby_Button_SendMessage", resourceCulture);
            }
        }
    }
}
