

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Database.Entity
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class BastaEntityModelContainer : DbContext
{
    public BastaEntityModelContainer()
        : base("name=BastaEntityModelContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Player> Players { get; set; }

    public virtual DbSet<Host> Hosts { get; set; }

    public virtual DbSet<AccessAccount> AccessAccounts { get; set; }

    public virtual DbSet<RoomConfiguration> RomConfigurations { get; set; }

    public virtual DbSet<Room> Rooms { get; set; }

}

}

