//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entity
{
    using System;
    
    public enum GameCategory : int
    {
        COUNTRY = 0,
        NAME = 1,
        LAST_NAME = 2,
        OBJECT = 3,
        COLOR = 4,
        BODY_PART = 5,
        TRADE = 6,
        FOOD = 7
    }
}
