
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Database.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Player
{

    public string email { get; set; }

    public short age { get; set; }

    public string country { get; set; }

    public Location location { get; set; }

    public string name { get; set; }

    public double score { get; set; }



    public virtual AccessAccount AccessAccount { get; set; }

}

}
